### ISSUE TITLE
Wings mod

### ISSUE THREAD

**Issue by kyleo1234** [ValkyrienSkies/Valkyrien-Skies#424] opened 2020-10-08 19:17 UTC
just found an odd bug with the mod wings where if its installed all blocks render one block below they should but are physically in the correct location so you are walking on the block but it appears its one block below you and you are floating in the air

**Comment by Rubydesic** [comment] 2020-10-08 19:33
Thank you so much for your report. This happens to be a duplicate of #382, which you may follow if you're interested.

**Closed by Rubydesic** 2020-10-08 19:33 UTC
