### ISSUE TITLE
Piston Glitch

### ISSUE THREAD

**Issue by Contri66** [ValkyrienSkies/Valkyrien-Skies#406] opened 2020-09-01 21:39 UTC
Version: Latest Curseforge

Issue: Ship flies erratically and becomes impossible to control.

How to re-create
1. build a ship with a normal physics infuser
2. place a sticky piston
3. power the piston
4. stand between the base of the piston and the head of it (inside of the piston up against the shaft)
5. close the piston

[here is a video](https://www.youtube.com/watch?v=FlBWm73TSaQ)

Initially found when playing around with slime blocks.

**Comment by Rubydesic** [comment] 2020-09-13 07:27
if only everyone made such beautiful and detailed bug reports

**Comment by Tri0de** [comment] 2020-09-25 22:53
This was caused by the piston adding negative mass to the ship. Its already fixed in 1.0.0.

**Closed by Tri0de** 2020-09-25 22:53 UTC
Labels: Category: Bug, Priority: Low
